"use client"
import Header from '@/Components/header'
import { Container } from 'react-bootstrap'
import { LuLayoutDashboard } from 'react-icons/lu'
import Dashbord from '@/Components/dashbord'
import Aside from '@/Components/aside'
import { useCookies } from 'react-cookie'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'
// import { db } from '../../firebaseConfig';
// import { collection, addDoc, setDoc, getDoc, doc, updateDoc } from "firebase/firestore";
import CityData from '@/data/city'

// export const metadata = {
//     title: 'Techkilla',
//     description: 'Generated by Techkilla',
// }
export default function Home() {
    const router = useRouter();
    const [cookies] = useCookies()
    useEffect(() => {
        console.log(cookies?.auth)
        if (!cookies?.auth) {
            router.push('/');
        }

        //  for (var i = 0; i < data.length; i++) {
        // const docRef = setDoc(doc(db, "Users", "a")).then({

        // })

        // const obj = data[i];
        // updateDoc(docRef, obj)
        //     .then(docRef => {
        //         console.log("A New Document Field has been added to an existing document: " + data[i].mail);
        //     })
        //     .catch(error => {
        //         console.log(error);
        //     })
        //  }

    }, [cookies?.auth, router])

    // const sayHello = async () => {

    //     for (var i = 0; i < data.length; i++) {
    //         const docRef = await setDoc(doc(db, "Users", data[i].mail.toLowerCase()), {

    //         });

    //         const obj = data[i];

    //         await setDoc(doc(db, "Users", obj.mail.toLowerCase()), {
    //             obj
    //         });

    //     }
    // }

    return (
        <>
            <div className="main">
                <Aside />
                <main>
                    <Header Heading={"Dashboard"} icon={<LuLayoutDashboard />} />
                    <Container>
                        <Dashbord data={CityData} />
                    </Container>
                    {/* <Button onClick={sayHello}>hello</Button> */}
                </main>
            </div>
        </>
    )
}
