"use client"
import React from 'react'

import Header from '../../../Components/header'
import { IoLocationOutline } from 'react-icons/io5'
import { Container } from 'react-bootstrap'
import Aside from '../../../Components/aside'
import CityTable from '../../../Components/settings/city'
export const metadata = {
    title: 'Techkilla',
    description: 'Generated by Techkilla',
  }
const City = ({ params }) => {
    console.log(params)
    return (
        <div className="main">
            <Aside />
            <main>
                <Header Heading={params?.building} isback={`/dashbord/${params?.city}/`} icon={<IoLocationOutline />} />
                <Container>
                    <CityTable city={'city'} />
                </Container>
            </main>
        </div>

    )
}

export default City
