"use client"
import React from 'react'

import Header from '@/Components/header'
import { IoLocationOutline } from 'react-icons/io5'
import { Container } from 'react-bootstrap'
import Aside from '@/Components/aside'
import CityTable from '@/Components/settings/city'
import { building } from '@/data/building'

// export const metadata = {
//     title: 'Techkilla',
//     description: 'Generated by Techkilla',
// }
const City = ({ params }) => {
    return (
        <div className="main">
            <Aside />
            <main>
                <Header Heading={params?.building} isback={`/dashbord/${params?.city}/`} icon={<IoLocationOutline />} />
                <Container>
                    <CityTable city={params?.city} building={params?.building} />
                </Container>
            </main>
        </div>

    )
}

export default City
